channels:
  - conda-forge
  - bioconda
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.11
  - tensorboard
  - numpy
  - pandas
  - pip
  - pip:
    - torch
    - torchvision
    - torchaudio
    - lightning
    - h5py
    - pyyaml
    - jinja2
    - scanpy
    - hydra-core
    - pytest
    - jupyterlab
    - matplotlib
    - tqdm
    - wandb>=0.12.10
    - rich
    - scipy
    - accelerate
    - requests
    - fire
    - geomloss
    - flash-attn
    - triton
