experiment:
  name: "vci_pretrain_${loss.name}_${model.nhead}_${model.nlayers}"
  local: "local"
  compiled: false
  deaware: false
  profile:
    enable_profiler: false
    profile_steps: [10, 100]
    max_steps: 110 # This is used only when profile is enabled
  num_epochs: 16
  num_nodes: 1
  num_gpus_per_node: 1
  port: 12399
  val_check_interval: 2000 # Number of steps between tests
  limit_val_batches: 0.005 # Use 1% of validation dataset
  checkpoint:
    path: /scratch/ctc/ML/vci/checkpoint/pretrain
    save_top_k: 4
    monitor: trainer/train_loss
    every_n_train_steps: 1000

wandb:
  enable: True
  project: "vci"

embeddings:
  esm2:
    embedding_file: /large_storage/ctc/ML/data/cell/misc/Homo_sapiens.GRCh38.gene_symbol_to_embedding_ESM2.pt
    cnt: 19790
    size: 5120
    # embedding_file: /large_storage/ctc/ML/data/cell/embs/Homo_sapiens.GRCh38.gene_symbol_to_embedding_Evo2_7B_mean.pt
    # cnt: 19790
    # size: 4096

validations:
  diff_exp:
    enable: true
    eval_interval_multiple: 10
    obs_pert_col: gene
    obs_filter_label: non-targeting
    top_k_rank: 200
    method: null
    dataset: /large_storage/ctc/datasets/vci/validation/rpe1_top5000_variable.h5ad
    dataset_name: rpe1_top5000_variable

  perturbation:
    enable: true
    eval_interval_multiple: 10
    pert_col: gene
    ctrl_label: non-targeting
    dataset: /large_storage/ctc/datasets/vci/validation/replogle_perturbation.h5ad
    dataset_name: replogle_perturbation

dataset:
  name: "vci"
  seed: 42
  num_train_workers: 8
  num_val_workers: 4
  train: /scratch/ctc/ML/uce/h5ad_train_dataset.csv
  val: /scratch/ctc/ML/uce/h5ad_val_dataset.csv
  data_dir: /large_experiments/goodarzilab/mohsen/cellxgene/processed
  # this is a map for each dataset's columns mapping them to a global gene ordering
  protein_emb_file_format: /large_storage/ctc/datasets/vci/training/gene_embidx_mapping.torch
  pad_length: 2048
  pad_token_idx: 0
  cls_token_idx: 3
  chrom_token_right_idx: 2
  P: 512
  N: 512
  num_cells:  36238464 # TODO: Is this required
  filter: false

  overrides:
    rpe1_top5000_variable: /large_storage/ctc/datasets/vci/validation/rpe1_top5000_variable.h5ad

tokenizer:
  token_dim: 5120

model:
  name: 'vci'
  batch_size: 128
  emsize: 512
  d_hid: 1024
  nhead: 16
  nlayers: 8
  dropout: 0.1
  output_dim:  512 # TODO: Is emsize different from this?
  use_flash_attention: true
  rda: false

task:
  mask: 0.2

optimizer:
  max_lr: 0.00024
  weight_decay: 0.01
  start: 1e-4
  end: 1.0
  max_grad_norm: 0.8
  gradient_accumulation_steps: 1

loss:
  name: "cross_entropy" # cross_entropy, cross_entropy, mse, wasserstein
  apply_normalization: False
