name: decoder_only
checkpoint: null
device: cuda

kwargs:
  hidden_dim: 512
  cell_sentence_len: 512
  loss: energy
  n_encoder_layers: 4
  n_decoder_layers: 4
  predict_residual: True
  softplus: False
  distributional_loss: energy
  transformer_backbone_key: GPT2
  transformer_backbone_kwargs:
      n_positions: 512 # just needs to be bigger than number of conditioning variables
      n_embd: 512
      d_inner: 1024
      n_layer: 8
      n_head: 8
      resid_pdrop: 0.0
      embd_pdrop: 0.0
      attn_pdrop: 0.0
      use_cache: false
