name: state
checkpoint: null
device: cuda

kwargs:
  cell_set_len: 128
  blur: 0.05
  hidden_dim: 672  # hidden dimension going into the transformer backbone
  loss: energy
  confidence_head: False
  n_encoder_layers: 4
  n_decoder_layers: 4
  predict_residual: True
  softplus: True
  freeze_pert: False
  transformer_decoder: False
  finetune_vci_decoder: False
  residual_decoder: False
  batch_encoder: False
  nb_decoder: False
  mask_attn: False
  use_effect_gating_token: False
  use_basal_projection: False
  distributional_loss: energy
  gene_decoder_bool: False
  init_from: null
  transformer_backbone_key: llama
  transformer_backbone_kwargs:
      max_position_embeddings: ${model.kwargs.cell_set_len}
      hidden_size: ${model.kwargs.hidden_dim}
      intermediate_size: 2688
      num_hidden_layers: 4
      num_attention_heads: 8
      num_key_value_heads: 8
      head_dim: 84
      use_cache: false
      attention_dropout: 0.0
      hidden_dropout: 0.0
      layer_norm_eps: 1e-6
      pad_token_id: 0
      bos_token_id: 1
      eos_token_id: 2
      tie_word_embeddings: false
      rotary_dim: 0
      use_rotary_embeddings: false


  grpo_mode: true
  grpo_config:
    # Gaussian Decoder 配置
    decoder_hidden_dim: 512
    
    # GRPO 采样和训练参数
    k_samples: 8          # 每次采样的候选数量
    ppo_eps: 0.5    #0.2      # PPO clipping 参数
    alpha_kl: 0.3   #0.1      # KL散度损失权重
    alpha_ent: 1e-4  #1e-4 #0.01        # 熵正则化权重
    alpha_sup: 10  #10.0        # 监督学习损失权重
    
    # 奖励函数权重
    reward_weights:        # MAE权重
      pds: 1.0             # PDS权重
      des: 1.0           # DES权重
    
    # 其他GRPO参数
    min_perts_for_pds: 3   # PDS计算的最小扰动数
    des_k_percentage: 0.1 #0.05  # DES计算的top-k基因比例