wandb_track: false
weight_decay: 0.0005
batch_size: 32
lr: 1.0e-05
max_steps: 20000
train_seed: 42
val_freq: 100
ckpt_every_n_steps: 2000
gradient_clip_val: 1 # 0 means no clipping
loss_fn: mse
devices: 2  # Number of GPUs to use for training
strategy: auto  # DDP strategy for multi-GPU training
# precision: bf16-mixed