# Generic wandb configuration
# Users should customize these values for their own use
entity: arcinstitute
project: vci1
local_wandb_dir: /large_storage/ctc/userspace/dhruvgautam/wandb/vci1
tags: [] 
